version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx.dockerfile
      args:
        TEST_STATIC_NODEJS_SERVER_PORT: ${TEST_STATIC_NODEJS_SERVER_PORT}
        TEST_DUMB_NGINX_CONTAINER_HOST: ${TEST_DUMB_NGINX_CONTAINER_HOST}
        TEST_PRERENDERER_NODEJS_SERVER_PORT: ${TEST_PRERENDERER_NODEJS_SERVER_PORT}
        TEST_SMART_NGINX_CONTAINER_HOST: ${TEST_SMART_NGINX_CONTAINER_HOST}
        TEST_APP_NODEJS_SERVER_PORT: ${TEST_APP_NODEJS_SERVER_PORT}
    volumes:
      - ./logs:/var/log/nginx
    networks:
      prerender:
        ipv4_address: 172.25.0.101
    extra_hosts:
      - ${TEST_SMART_NGINX_CONTAINER_HOST}:170.0.0.1
      - ${TEST_DUMB_NGINX_CONTAINER_HOST}:170.0.0.1
      - ${TEST_NODEJS_CONTAINER_HOST}:172.25.0.102

  tests:
    depends_on:
      - nginx
    build:
      context: .
      dockerfile: docker/tests/tests-node-12.dockerfile
    extra_hosts:
      - ${TEST_SMART_NGINX_CONTAINER_HOST}:172.25.0.101
      - ${TEST_DUMB_NGINX_CONTAINER_HOST}:172.25.0.101
      - ${TEST_NODEJS_CONTAINER_HOST}:127.0.0.1
    volumes:
      - ./logs:/var/www/logs
      - ./dist:/var/www/dist
      - ./src:/var/www/src
      - ./test:/var/www/test
    ports:
      - 9229:9229
    networks:
      prerender:
        ipv4_address: 172.25.0.102
    command: npm run test:debug

networks:
  prerender:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
