version: '2.2'

services:
  apache:
    build:
      context: .
      dockerfile: docker/apache/apache.dockerfile
      args:
        TEST_SMART_APACHE_CONTAINER_HOST: ${TEST_SMART_APACHE_CONTAINER_HOST}
        TEST_DUMB_APACHE_CONTAINER_HOST: ${TEST_DUMB_APACHE_CONTAINER_HOST}
        TEST_PRERENDERER_NODEJS_SERVER_PORT: ${TEST_PRERENDERER_NODEJS_SERVER_PORT}
        TEST_STATIC_NODEJS_SERVER_PORT: ${TEST_STATIC_NODEJS_SERVER_PORT}
        TEST_APP_NODEJS_SERVER_PORT: ${TEST_APP_NODEJS_SERVER_PORT}
    environment:
      - TEST_SMART_APACHE_CONTAINER_HOST
      - TEST_DUMB_APACHE_CONTAINER_HOST
      - TEST_PRERENDERER_NODEJS_SERVER_PORT
      - TEST_STATIC_NODEJS_SERVER_PORT
      - TEST_APP_NODEJS_SERVER_PORT
    volumes:
      - ./logs/apache:/usr/local/apache2/logs
    networks:
      prerenderer:
        ipv4_address: 173.20.0.100
        ipv6_address: 2002:ac14:0:0:0:0:0:100
    extra_hosts:
      - ${TEST_NODEJS_CONTAINER_HOST}:173.20.0.102
      - ${TEST_NODEJS_CONTAINER_HOST}:2002:ac14:0:0:0:0:0:102

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx.dockerfile
      args:
        TEST_SMART_NGINX_CONTAINER_HOST: ${TEST_SMART_NGINX_CONTAINER_HOST}
        TEST_DUMB_NGINX_CONTAINER_HOST: ${TEST_DUMB_NGINX_CONTAINER_HOST}
        TEST_PRERENDERER_NODEJS_SERVER_PORT: ${TEST_PRERENDERER_NODEJS_SERVER_PORT}
        TEST_STATIC_NODEJS_SERVER_PORT: ${TEST_STATIC_NODEJS_SERVER_PORT}
        TEST_APP_NODEJS_SERVER_PORT: ${TEST_APP_NODEJS_SERVER_PORT}
    environment:
      - TEST_SMART_NGINX_CONTAINER_HOST
      - TEST_DUMB_NGINX_CONTAINER_HOST
      - TEST_PRERENDERER_NODEJS_SERVER_PORT
      - TEST_STATIC_NODEJS_SERVER_PORT
      - TEST_APP_NODEJS_SERVER_PORT
    networks:
      prerenderer:
        ipv4_address: 173.20.0.101
        ipv6_address: 2002:ac14:0:0:0:0:0:101
    extra_hosts:
      - ${TEST_NODEJS_CONTAINER_HOST}:173.20.0.102
      - ${TEST_NODEJS_CONTAINER_HOST}:2002:ac14:0:0:0:0:0:102

  tests:
    depends_on:
      - nginx
    build:
      context: .
      dockerfile: docker/tests/tests-node-${NODE_VERSION}.dockerfile
    extra_hosts:
      - ${TEST_SMART_APACHE_CONTAINER_HOST}:173.20.0.100
      - ${TEST_DUMB_APACHE_CONTAINER_HOST}:173.20.0.100
      - ${TEST_SMART_NGINX_CONTAINER_HOST}:173.20.0.101
      - ${TEST_DUMB_NGINX_CONTAINER_HOST}:173.20.0.101
      - ${TEST_NODEJS_CONTAINER_HOST}:127.0.0.1
      - ${TEST_SMART_NGINX_CONTAINER_HOST}:2002:ac14:0:0:0:0:0:101
      - ${TEST_DUMB_NGINX_CONTAINER_HOST}:2002:ac14:0:0:0:0:0:101
      - ${TEST_NODEJS_CONTAINER_HOST}:::1
    networks:
      prerenderer:
        ipv4_address: 173.20.0.102
        ipv6_address: 2002:ac14:0:0:0:0:0:102
    environment:
      - PRERENDERER_LOG_FILE
      - CHROMIUM_EXECUTABLE
      - NODE_ENV
      - SNAPSHOTS_DRIVER
      - SNAPSHOTS_DIRECTORY
      - TEST_SMART_APACHE_CONTAINER_HOST
      - TEST_DUMB_APACHE_CONTAINER_HOST
      - TEST_DUMB_NGINX_CONTAINER_HOST
      - TEST_SMART_NGINX_CONTAINER_HOST
      - TEST_NODEJS_CONTAINER_HOST
      - TEST_APP_NODEJS_SERVER_PORT
      - TEST_APP_NODEJS_SERVER_PORT_SECURE
      - TEST_STATIC_NODEJS_SERVER_PORT
      - TEST_PRERENDERER_NODEJS_SERVER_PORT

networks:
  prerenderer:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 173.20.0.0/24
          gateway: 173.20.0.1
        - subnet: 2002:ac14:0000::/48
          gateway: 2002:ac14:0:0:0:0:0:1
